# Generated by Django 2.2.3 on 2019-08-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, choices=[('P', 'Programming'), ('E', 'Engineering'), ('B', 'Business')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stud_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
